/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.AlojamentoControl;
import Model.SoNumeros;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author android
 */
public class CadAlojamento extends javax.swing.JFrame {

//    private boolean salvou;
    
    public CadAlojamento() {
        initComponents();
        String data = pegaData();
        campoData.setText(data);
        controlAloj = new AlojamentoControl();
        campoNumeroCama.setDocument(new SoNumeros());
        campoNumeroQuarto.setDocument(new SoNumeros());
    }
    /**
     * Creates new form Alojamento
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    private String pegaData(){
          DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        return dtf.format(LocalDateTime.now());
    }
    public void recebePessoa(String idPessoa, String nomePessoa){
        campoCodigo.setText(idPessoa);
        campoNome.setText(nomePessoa);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAlojamento = new javax.swing.JLabel();
        Painel = new javax.swing.JPanel();
        txtNumeroQuarto = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        BotaoSalvar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JLabel();
        txtNumeroCama = new javax.swing.JLabel();
        campoData = new javax.swing.JFormattedTextField();
        campoCodigo = new javax.swing.JFormattedTextField();
        btnBusca = new javax.swing.JButton();
        campoNumeroCama = new javax.swing.JTextField();
        campoNumeroQuarto = new javax.swing.JTextField();
        BotaoVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        txtAlojamento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtAlojamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAlojamento.setText("Cadastrar Alojamento");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Alojamento");

        Painel.setBackground(new java.awt.Color(255, 255, 255));
        Painel.setForeground(new java.awt.Color(204, 255, 255));

        txtNumeroQuarto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtNumeroQuarto.setText("Nº Quarto:");

        txtNome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtNome.setText("Nome:");

        txtData.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtData.setText("Data:");

        BotaoSalvar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotaoSalvar.setText("Cadastrar");
        BotaoSalvar.setActionCommand("Cadastrar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtCodigo.setText("Código:");

        txtNumeroCama.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtNumeroCama.setText("Nº Cama:");

        campoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataActionPerformed(evt);
            }
        });

        campoCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        btnBusca.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnBusca.setText("Buscar Pessoa");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        campoNumeroCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroCamaActionPerformed(evt);
            }
        });

        campoNumeroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroQuartoActionPerformed(evt);
            }
        });

        BotaoVoltar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.setMaximumSize(new java.awt.Dimension(86, 21));
        BotaoVoltar.setMinimumSize(new java.awt.Dimension(86, 21));
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Alojamento");

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(txtNumeroCama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNumeroCama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(txtCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBusca))
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(txtData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(txtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(txtNumeroQuarto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNumeroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BotaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca))
                .addGap(18, 18, 18)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCama)
                    .addComponent(campoNumeroCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroQuarto)
                    .addComponent(campoNumeroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        campoCodigo.requestFocus();
        // Validação 
       
        if (campoCodigo.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Digite o código!");
            campoCodigo.requestFocus();
        }
        else if (campoNome.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Digite o nome completo!");
            campoNome.requestFocus();
        }
        else if (campoNumeroCama.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Digite o número da cama!");
            campoNumeroCama.requestFocus();
        }
        else if (campoNumeroQuarto.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Digite o número do quarto!");
            campoNumeroQuarto.requestFocus();
        }
        else {
            String data = (String)campoData.getText();
            //System.out.println("Data: "+data);
            int vagas = controlAloj.RetornaQuantidadeVagas();
            //System.out.println("vagas: "+vagas);
            int contData = controlAloj.RetornaQuantidadeData(data);
            //System.out.println("countData: "+contData);
            int codigo=Integer.parseInt((String)campoCodigo.getText());
            //System.out.println("Pessoa: "+codigo);
            if(vagas <= contData){
                JOptionPane.showMessageDialog(null, "Quartos Lotados!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                campoCodigo.setText("");
                campoNome.setText("");
                campoNumeroQuarto.setText("");
                campoNumeroCama.setText("");
                //dispose();
            }
            else{
                boolean verifica = VerificaAlojado(codigo, data);
                if(verifica==true){
                    JOptionPane.showMessageDialog(null, "Pessoa se encontra Alojada!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    int idPessoa = Integer.parseInt((String)campoCodigo.getText());
                    data = campoData.getText();
                    int nQuarto = Integer.parseInt((String)campoNumeroQuarto.getText());
                    int nCama = Integer.parseInt((String)campoNumeroCama.getText());

                    controlAloj.CadastrarAlojamento(idPessoa, data, nQuarto, nCama);

                    JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!", "Cadastrado", JOptionPane.INFORMATION_MESSAGE);
                    campoCodigo.setText("");
                    campoNome.setText("");
                    campoNumeroQuarto.setText("");
                    campoNumeroCama.setText("");
                    //this.salvou = true;
                }
                //dispose(); //fecha modal
            }
        }
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private boolean VerificaAlojado(int id, String data){
        boolean verificaA = controlAloj.RetornaPessoaData(id, data);
        return verificaA;
    }
    
    private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataActionPerformed

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed

        // TODO add your handling code here:
        ListarPessoas objconsulta = new ListarPessoas(this);
        objconsulta.setVisible(true);
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void campoNumeroCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroCamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroCamaActionPerformed

    private void campoNumeroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroQuartoActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAlojamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAlojamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAlojamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAlojamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CadAlojamento().setVisible(true);
            }
        });
    }
private AlojamentoControl controlAloj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JPanel Painel;
    private javax.swing.JButton btnBusca;
    private javax.swing.JFormattedTextField campoCodigo;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumeroCama;
    private javax.swing.JTextField campoNumeroQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtAlojamento;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNumeroCama;
    private javax.swing.JLabel txtNumeroQuarto;
    // End of variables declaration//GEN-END:variables

   
}
