/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ItemControl;
import Model.Item;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NoteC
 */
public class ListItem extends javax.swing.JFrame {
    /**
     * Creates new form ListItem
     */
    public ListItem() {
        initComponents();
        controItem = new ItemControl();
    }
    
    public ListItem(CadDoacao doacao) {
        initComponents();
        controItem = new ItemControl();
        this.doacao=doacao;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTItem = new javax.swing.JTable();
        jBExcluir = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista Ítens");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(468, 338));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listar Itens");

        jTItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTItem);

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBSelecionar.setText("Selecionar");
        jBSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jBExcluir)
                                .addGap(30, 30, 30)
                                .addComponent(jBCadastrar)
                                .addGap(27, 27, 27)
                                .addComponent(jBEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSelecionar)
                                .addGap(18, 18, 18)
                                .addComponent(jBVoltar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBCadastrar)
                    .addComponent(jBVoltar)
                    .addComponent(jBEditar)
                    .addComponent(jBSelecionar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        //System.out.println("Voltar!");
        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Atualiza();
        
    }//GEN-LAST:event_formWindowOpened

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        //System.out.println("Excluir!");
        if(jTItem.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma Ítem para Excluir", "Atenção", JOptionPane.ERROR_MESSAGE );
        }
        else{
            int row = jTItem.getSelectedRow();
            int codigo = Integer.parseInt((String)jTItem.getValueAt(row,0));
            String nome = (String)jTItem.getValueAt(row,1);
            
            if (JOptionPane.showConfirmDialog(null, "Deseja Excluir o "+nome+"?","EXCLUIR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                //System.out.println(codigo + " " + nome);
                controItem.ExcluirItem(codigo);
                JOptionPane.showMessageDialog(null, nome+" Excluído com Sucesso!", "EXCLUIR", JOptionPane.WARNING_MESSAGE);
                Atualiza();
            }
            else{
                JOptionPane.showMessageDialog(null, nome+" Não Excluído!", "EXCLUIR" ,JOptionPane.WARNING_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        //System.out.println("Cadastrar!");
        CadItens retornoItem = new CadItens(this);
        retornoItem.setVisible(true);
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        //System.out.println("Editar!");
        if(jTItem.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma Ítem para Editar", "ATENÇÃO", JOptionPane.ERROR_MESSAGE );
        }
        else{
            int row = jTItem.getSelectedRow();
            int codigo = Integer.parseInt((String)jTItem.getValueAt(row,0));
            String nome = JOptionPane.showInputDialog("Digite o nome do Ítem");
            
            if (JOptionPane.showConfirmDialog(null, "Deseja Editar para "+nome+"?","EDITAR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                //System.out.println(codigo + " " + nome);
                controItem.AlterarItem(codigo, nome);
                JOptionPane.showMessageDialog(null, nome+" Editado com Sucesso!", "EDITAR", JOptionPane.WARNING_MESSAGE);
                Atualiza();
            }
            else{
                JOptionPane.showMessageDialog(null, nome+" Não Editado!", "EDITAR" ,JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelecionarActionPerformed
        // TODO add your handling code here:
        //System.out.println("Selecionar!");
         if(jTItem.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
        int row = jTItem.getSelectedRow();
        String codigo = jTItem.getValueAt(row,0).toString().trim();
        String nomeItem = jTItem.getValueAt(row,1).toString().trim();
        
        
        doacao.recebeItem(codigo, nomeItem);
        dispose();
    }//GEN-LAST:event_jBSelecionarActionPerformed

    public void Atualiza(){
        DefaultTableModel mp1 = (DefaultTableModel) jTItem.getModel();
        
        int l = mp1.getRowCount();
        
        if(l>0){
            while(l>0){
                ((DefaultTableModel) jTItem.getModel()).removeRow(l-1);
                l--;
            }
        }
        
        ArrayList<Item> lista = new ArrayList<Item>();
        lista = controItem.getListaItem();
        DefaultTableModel mp = (DefaultTableModel) jTItem.getModel();
        
        for(Item i : lista){
            //System.out.println(i.getIdItem()+" "+i.getNomeItem());
            String Coluna0 = String.valueOf(i.getIdItem());
            String Coluna1 = i.getNomeItem();
            
            mp.addRow(new String[] {Coluna0,Coluna1});
        }
        jTItem.setAutoCreateRowSorter(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListItem().setVisible(true);
            }
        });
        
    }

    private ItemControl controItem;
    public CadDoacao doacao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSelecionar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTItem;
    // End of variables declaration//GEN-END:variables
}
