/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Control.PessoaControl;
import Dao.PessoaDao;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author android
 */
public class ListarPessoas extends javax.swing.JFrame {
    
    PessoaControl control = new PessoaControl();
    CadAlojamento alojamento;
    ListAlojamento listAlojamento;

    /**
     * Creates new form ListarPessoas
     */
    public ListarPessoas() {
        initComponents();
    }
    
    public ListarPessoas(CadAlojamento alojamento) {
        initComponents();
        this.alojamento = alojamento;
    }
    
    public ListarPessoas(ListAlojamento listAlojamento) {
        initComponents();
        this.listAlojamento = listAlojamento;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoNomeBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBSelectAloja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista Pessoas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buscar Pessoa");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel1.setText("Nome:");

        campoNomeBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNomeBuscaKeyReleased(evt);
            }
        });

        jtbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Cidade", "Observação", "Gênero"
            }
        ));
        jScrollPane1.setViewportView(jtbl);

        jButton1.setText("Selecionar Pessoa");
        jButton1.setPreferredSize(new java.awt.Dimension(90, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Após selecionar a pessoa clique no botão abaixo");

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cadastrar Pessoa");
        jButton3.setPreferredSize(new java.awt.Dimension(122, 22));

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBSelectAloja.setText("Seleciona Alojado");
        jBSelectAloja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelectAlojaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBSelectAloja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(58, 58, 58)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(campoNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jBEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSelectAloja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jtbl.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha" );
       }
        int row = jtbl.getSelectedRow();
        String codigo = jtbl.getValueAt(row,0).toString().trim();
        String nome = jtbl.getValueAt(row,1).toString().trim();
        
        
        alojamento.recebePessoa(codigo, nome);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void atualizaPessoas(){
        DefaultTableModel mp1 = (DefaultTableModel) jtbl.getModel();
        
        int l = mp1.getRowCount();
        
        if(l>0){
            while(l>0){
                ((DefaultTableModel) jtbl.getModel()).removeRow(l-1);
                l--;
            }
        }
        
        try{
            ResultSet rs = control.TodasPessoas();
            
            DefaultTableModel mp = (DefaultTableModel) jtbl.getModel();
            
            while(rs.next()){
                String Coluna0=rs.getString("idPessoa").toString().trim();
                String Coluna1=rs.getString("nomePessoa").toString().trim();
                String Coluna2=rs.getString("cpfPessoa").toString().trim();
                String Coluna3=rs.getString("cidade").toString().trim();
                String Coluna4=rs.getString("observacao").toString().trim();
                String Coluna5=rs.getString("genero").toString().trim();
                
                mp.addRow(new String[] {Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5});
            
        }
       }
        catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, "erro:"+ex);
                } catch (IOException ex) {
            Logger.getLogger(ListarPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtbl.setAutoCreateRowSorter(true);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
        DefaultTableModel mp1 = (DefaultTableModel) jtbl.getModel();
        
        int l = mp1.getRowCount();
        
        if(l>0){
            while(l>0){
                ((DefaultTableModel) jtbl.getModel()).removeRow(l-1);
                l--;
            }
        }
        
        try{
            ResultSet rs = control.TodasPessoas();
            
            DefaultTableModel mp = (DefaultTableModel) jtbl.getModel();
            
            while(rs.next()){
                String Coluna0=rs.getString("idPessoa").toString().trim();
                String Coluna1=rs.getString("nomePessoa").toString().trim();
                String Coluna2=rs.getString("cpfPessoa").toString().trim();
                String Coluna3=rs.getString("cidade").toString().trim();
                String Coluna4=rs.getString("observacao").toString().trim();
                String Coluna5=rs.getString("genero").toString().trim();
                
                mp.addRow(new String[] {Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5});
            
        }
       }
        catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, "erro:"+ex);
                } catch (IOException ex) {
            Logger.getLogger(ListarPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtbl.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        atualizaPessoas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void campoNomeBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeBuscaKeyReleased
        // TODO add your handling code here:
        String tipo =" "+"nomePessoa";
        
        String arg = campoNomeBusca.getText();
        
        DefaultTableModel mp1 = (DefaultTableModel) jtbl.getModel();
        int l = mp1.getRowCount();
        
        if(l>0){
            while(l>0){
                ((DefaultTableModel) jtbl.getModel()).removeRow(l-1);
                l--;
            }
        }
        
        try{
            ResultSet rs = control.PessoaPorNome(arg);
            
            DefaultTableModel mp = (DefaultTableModel) jtbl.getModel();
            
            while(rs.next()){
                String Coluna0=rs.getString("idPessoa").toString().trim();
                String Coluna1=rs.getString("nomePessoa").toString().trim();
                String Coluna2=rs.getString("cpfPessoa").toString().trim();
                String Coluna3=rs.getString("cidade").toString().trim();
                String Coluna4=rs.getString("observacao").toString().trim();
                String Coluna5=rs.getString("genero").toString().trim();
                
                mp.addRow(new String[] {Coluna0,Coluna1,Coluna2,Coluna3,Coluna4,Coluna5});
            
        }
       }
        catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, "erro:"+ex);
                } catch (IOException ex) {
            Logger.getLogger(ListarPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtbl.setAutoCreateRowSorter(true);
        
        
        
    }//GEN-LAST:event_campoNomeBuscaKeyReleased

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
       
        
        int row = jtbl.getSelectedRow();
        String codigo = jtbl.getValueAt(row,0).toString().trim();
        String nome = jtbl.getValueAt(row,1).toString().trim();
        String cpf = jtbl.getValueAt(row,2).toString().trim();
        String cidade = jtbl.getValueAt(row,3).toString().trim();
        String observacao = jtbl.getValueAt(row,4).toString().trim();
        String genero = jtbl.getValueAt(row,5).toString().trim();
        int id = Integer.parseInt(codigo);
        AtualizaPessoa obj = new AtualizaPessoa(id,nome,cpf,cidade,observacao,genero);
        obj.setVisible(true);
        atualizaPessoas();
        
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        if(jtbl.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione um Doador para Excluir", "Atenção", JOptionPane.ERROR_MESSAGE );
        }
        else{
            int row = jtbl.getSelectedRow();
            int codigo = Integer.parseInt((String)jtbl.getValueAt(row,0));
            String nome = (String)jtbl.getValueAt(row,1);

            if (JOptionPane.showConfirmDialog(null, "Deseja Excluir o "+nome+"?","EXCLUIR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                try {
                    //System.out.println(codigo + " " + nome);
                    control.ExcluirPessoa(codigo);
                } catch (Exception ex) {
                    Logger.getLogger(ListarPessoas.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, nome+" Excluído com Sucesso!", "EXCLUIR", JOptionPane.WARNING_MESSAGE);
                atualizaPessoas();
            }
            else{
                JOptionPane.showMessageDialog(null, nome+" Não Excluído!", "EXCLUIR" ,JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBSelectAlojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelectAlojaActionPerformed
        // TODO add your handling code here:
        if(jtbl.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE );
        }
        
        int row = jtbl.getSelectedRow();
        int codigo = Integer.parseInt(jtbl.getValueAt(row,0).toString().trim());
        String nome = jtbl.getValueAt(row,1).toString().trim();
        String cpf = jtbl.getValueAt(row,2).toString().trim();
        String cidade = jtbl.getValueAt(row,3).toString().trim();
        String genero = jtbl.getValueAt(row,5).toString().trim();
        
        listAlojamento.recebePessoa(codigo, nome, cpf, cidade, genero);
        listAlojamento.ListaAloja();
        
        dispose();
    }//GEN-LAST:event_jBSelectAlojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNomeBusca;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSelectAloja;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl;
    // End of variables declaration//GEN-END:variables
}
