/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.VagasControl;
import Model.SoNumeros;
import javax.swing.JOptionPane;

/**
 *
 * @author android
 */
public class Vagas extends javax.swing.JFrame {

//    private boolean salvou;

    /**
     * Creates new form Vagas
     */
    public Vagas() {
        initComponents();
        controlVagas = new VagasControl();
        campoNumeroTotalCamas.setDocument(new SoNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtInformeQuantidadeCamasUnidade = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        campoNumeroTotalCamas = new javax.swing.JTextField();
        txtQuantidadeCamasUnidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vagas");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtInformeQuantidadeCamasUnidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInformeQuantidadeCamasUnidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInformeQuantidadeCamasUnidade.setText("Informe a quantidade de camas disponíveis na unidade");

        jButtonSalvar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        campoNumeroTotalCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroTotalCamasActionPerformed(evt);
            }
        });

        txtQuantidadeCamasUnidade.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantidadeCamasUnidade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtQuantidadeCamasUnidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuantidadeCamasUnidade.setText("Quantidade de camas na unidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(campoNumeroTotalCamas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txtQuantidadeCamasUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInformeQuantidadeCamasUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtQuantidadeCamasUnidade)
                .addGap(18, 18, 18)
                .addComponent(txtInformeQuantidadeCamasUnidade)
                .addGap(27, 27, 27)
                .addComponent(campoNumeroTotalCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        // Validação 
        if (campoNumeroTotalCamas.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de camas disponíveis!");
            campoNumeroTotalCamas.requestFocus();
        }
        else {
            
            int campoNumeroTotalCamas = Integer.parseInt(this.campoNumeroTotalCamas.getText()); 
//           
            controlVagas.AlterarVagas(campoNumeroTotalCamas);
            dispose();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void campoNumeroTotalCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroTotalCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroTotalCamasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Vagas().setVisible(true);
            }
        });
    }
    private VagasControl  controlVagas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNumeroTotalCamas;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtInformeQuantidadeCamasUnidade;
    private javax.swing.JLabel txtQuantidadeCamasUnidade;
    // End of variables declaration//GEN-END:variables
}
