/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.DoadorControl;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/**
 *
 * @author android
 */
public class AtualizaDoador extends javax.swing.JFrame {
   int idDoador;
   String nomeDoador;
   String telefone;
   String cpf;
   String genero;
   DoadorControl controlDoador = new DoadorControl();
   
    /**
     * Creates new form doador
     */
    public AtualizaDoador() {
        initComponents();
       
    }
    
    
    public AtualizaDoador(int id,String nome,String telefone,String cpf,String genero){
        initComponents();
        this.idDoador = id;
        this.nomeDoador = nome;
        this.telefone = telefone;
        this.cpf = cpf;
        this.genero = genero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTituloDoador = new javax.swing.JLabel();
        jLabelNomeDoador = new javax.swing.JLabel();
        jPanelSexoDoador = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabelTelefoneDoador = new javax.swing.JLabel();
        jLabelCPFDoador = new javax.swing.JLabel();
        textNomeDoador = new javax.swing.JTextField();
        textCPFDoador = new javax.swing.JFormattedTextField();
        jBCadastrarDoador = new javax.swing.JButton();
        jBVoltarDoador = new javax.swing.JButton();
        textTelefoneDoador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualiza Doador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTituloDoador.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabelTituloDoador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloDoador.setText("Atualizar Doador");
        jLabelTituloDoador.setToolTipText("");
        jLabelTituloDoador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNomeDoador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabelNomeDoador.setText("Nome*:");

        jPanelSexoDoador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSexoDoador.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanelSexoDoador.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jRadioButton1.setText("Masculino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jRadioButton2.setText("Feminino");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSexoDoadorLayout = new javax.swing.GroupLayout(jPanelSexoDoador);
        jPanelSexoDoador.setLayout(jPanelSexoDoadorLayout);
        jPanelSexoDoadorLayout.setHorizontalGroup(
            jPanelSexoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSexoDoadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addContainerGap())
            .addGroup(jPanelSexoDoadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSexoDoadorLayout.setVerticalGroup(
            jPanelSexoDoadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSexoDoadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTelefoneDoador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabelTelefoneDoador.setText("Telefone:");

        jLabelCPFDoador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabelCPFDoador.setText("CPF:");

        textNomeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeDoadorActionPerformed(evt);
            }
        });

        try {
            textCPFDoador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jBCadastrarDoador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBCadastrarDoador.setText("Cadastrar");
        jBCadastrarDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarDoadorActionPerformed(evt);
            }
        });

        jBVoltarDoador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBVoltarDoador.setText("Voltar");
        jBVoltarDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarDoadorActionPerformed(evt);
            }
        });

        textTelefoneDoador.setText("( )");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBCadastrarDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBVoltarDoador))
                    .addComponent(jLabelTituloDoador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNomeDoador)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textNomeDoador)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefoneDoador)
                                    .addComponent(textTelefoneDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCPFDoador)
                                    .addComponent(textCPFDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanelSexoDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCPFDoador)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textCPFDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNomeDoador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTelefoneDoador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textTelefoneDoador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCadastrarDoador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVoltarDoador, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void textNomeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeDoadorActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jBVoltarDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarDoadorActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBVoltarDoadorActionPerformed

    private void jBCadastrarDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarDoadorActionPerformed
        // TODO add your handling code here:
         String sexo="";
        if (textNomeDoador.getText().equals("")||textTelefoneDoador.getText().equals("")||textCPFDoador.getText().equals("")||(jRadioButton1.isSelected()!=true&&jRadioButton2.isSelected()!=true)){
            JOptionPane.showMessageDialog(rootPane, "Preencher os Campos em Branco!", "ATENÇÃO" ,JOptionPane.ERROR_MESSAGE);
        }
        else{
            String nomenovo = textNomeDoador.getText();
            
            String fonenovo = textTelefoneDoador.getText();
            String cpfnovo = textCPFDoador.getText();
            String cpf=(String)textCPFDoador.getText();
            //System.out.println(cpf);
            cpf=cpf.replaceAll("\\.","");
            //System.out.println(cpf);
            cpf=cpf.replaceAll("-","");
            //System.out.println(cpf);
            
            if (isCPF(cpf) == true){
                
                cpf=(String)textCPFDoador.getText();
                if (VerificarCpf(cpf) == false){
                    //System.out.println("Nome do Doador Digitado: " + textNomeDoador.getText());
                    //System.out.println("Telefone do Doador Digitado: " + textTelefoneDoador.getText());
                    //System.out.println("CPF do Doador Digitado: " + textCPFDoador.getText());
                    //System.out.println("Sexo: " + jRadioButton1);
                    if(jRadioButton1.isSelected()==true){
                        //System.out.println("Sexo: Masculino");
                        sexo="Masculino";
                    }
                    else{
                        //System.out.println("Sexo: Feminino");
                        sexo="Feminino";
                    }
                    controlDoador.AlterarDoador(idDoador,nomenovo, fonenovo, cpfnovo, sexo);
                    JOptionPane.showMessageDialog(rootPane, "Doador Cadastrado com Sucesso!", "Cadastrado" ,JOptionPane.INFORMATION_MESSAGE);
                    textNomeDoador.setText("");
                    textTelefoneDoador.setText("");
                    textCPFDoador.setText("");
                    doadores.atualizarDoadores();
                    //dispose();
                }
                else{
                    textCPFDoador.setText("");
                    textCPFDoador.requestFocus();
                    JOptionPane.showMessageDialog(rootPane, "CPF Existente!", "ATENÇÃO" ,JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                textCPFDoador.setText("");
                textCPFDoador.requestFocus();
                JOptionPane.showMessageDialog(rootPane, "CPF Inválido!", "ATENÇÃO" ,JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBCadastrarDoadorActionPerformed
private boolean VerificarCpf (String cpf){
        boolean verifica = controlDoador.VerificaCpf(cpf);
        return verifica;
    }
    private static boolean isCPF(String CPF) {
        // considera-se erro CPF's formados por uma sequencia de numeros iguais
        if (CPF.equals("00000000000") ||
            CPF.equals("11111111111") ||
            CPF.equals("22222222222") || CPF.equals("33333333333") ||
            CPF.equals("44444444444") || CPF.equals("55555555555") ||
            CPF.equals("66666666666") || CPF.equals("77777777777") ||
            CPF.equals("88888888888") || CPF.equals("99999999999") ||
            (CPF.length() != 11)){
            return(false);
        }
        
        char dig10, dig11;
        int sm, i, r, num, peso;

        // "try" - protege o codigo para eventuais erros de conversao de tipo (int)
        try {
            // Calculo do 1o. Digito Verificador
            sm = 0;
            peso = 10;
            for (i=0; i<9; i++) {
            // converte o i-esimo caractere do CPF em um numero:
            // por exemplo, transforma o caractere '0' no inteiro 0
            // (48 eh a posicao de '0' na tabela ASCII)
            num = (int)(CPF.charAt(i) - 48);
            sm = sm + (num * peso);
            peso = peso - 1;
            }

            r = 11 - (sm % 11);
            if ((r == 10) || (r == 11)){
                dig10 = '0';
            }
            else {
                dig10 = (char)(r + 48);
            } // converte no respectivo caractere numerico

            // Calculo do 2o. Digito Verificador
            sm = 0;
            peso = 11;
            for(i=0; i<10; i++) {
            num = (int)(CPF.charAt(i) - 48);
            sm = sm + (num * peso);
            peso = peso - 1;
            }

            r = 11 - (sm % 11);
            if ((r == 10) || (r == 11)){
                 dig11 = '0';
            }
            else {
                dig11 = (char)(r + 48);
            }

        // Verifica se os digitos calculados conferem com os digitos informados.
            if ((dig10 == CPF.charAt(9)) && (dig11 == CPF.charAt(10))){
                 return(true);
            }
            else{
                return(false);
            }
        } 
        catch (InputMismatchException erro){
            return(false);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        textNomeDoador.setText(nomeDoador);
        textCPFDoador.setText(cpf);
        textTelefoneDoador.setText(telefone);
        if(genero.equalsIgnoreCase("Masculino"))
            {
                jRadioButton1.setSelected(true);
            }
            else{
                jRadioButton2.setSelected(true);
            }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizaDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizaDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizaDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizaDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizaDoador().setVisible(true);
            }
        });
    }

    private DoadorControl controDoador;
    public ListarDoadores doadores;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCadastrarDoador;
    private javax.swing.JButton jBVoltarDoador;
    private javax.swing.JLabel jLabelCPFDoador;
    private javax.swing.JLabel jLabelNomeDoador;
    private javax.swing.JLabel jLabelTelefoneDoador;
    private javax.swing.JLabel jLabelTituloDoador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSexoDoador;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JFormattedTextField textCPFDoador;
    private javax.swing.JTextField textNomeDoador;
    private javax.swing.JTextField textTelefoneDoador;
    // End of variables declaration//GEN-END:variables
}
