/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ItemControl;
import javax.swing.JOptionPane;

/**
 *
 * @author android
 */
public class CadItens extends javax.swing.JFrame {

    /**
     * Creates new form CadItens
     */
    
    public CadItens() {
        initComponents();
        controItem = new ItemControl();
    }

    public CadItens(ListItem itens) {
        initComponents();
        controItem = new ItemControl();
        this.itens = itens;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloItem = new javax.swing.JLabel();
        jLabelNomeItem = new javax.swing.JLabel();
        textNomeItem = new javax.swing.JTextField();
        JBSalvarItem = new javax.swing.JButton();
        jBVoltarItem = new javax.swing.JButton();
        jBListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastra Ítens");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTituloItem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabelTituloItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloItem.setText("Cadastrar Itens");

        jLabelNomeItem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabelNomeItem.setText("Nome*:");

        textNomeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeItemActionPerformed(evt);
            }
        });

        JBSalvarItem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        JBSalvarItem.setText("Cadastrar");
        JBSalvarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarItemActionPerformed(evt);
            }
        });

        jBVoltarItem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBVoltarItem.setText("Voltar");
        jBVoltarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarItemActionPerformed(evt);
            }
        });

        jBListar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBListar.setText("Listar");
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNomeItem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBSalvarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jBListar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(jBVoltarItem))
                            .addComponent(textNomeItem))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNomeItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSalvarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVoltarItem)
                    .addComponent(jBListar))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeItemActionPerformed
        
    }//GEN-LAST:event_textNomeItemActionPerformed

    private void JBSalvarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarItemActionPerformed
        boolean verifica=false;
        
        if (textNomeItem.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo em Branco", "ATENÇÃO" ,JOptionPane.ERROR_MESSAGE);
            textNomeItem.requestFocus();
        }
        else{
            //System.out.println("Nome do Ítem Digitado: " + textNomeItem.getText());
            verifica = controItem.CadastrarItem(textNomeItem.getText());
            if (verifica==false){
                JOptionPane.showMessageDialog(null, "Ítem Existente", "CADASTRAR" ,JOptionPane.WARNING_MESSAGE);
                textNomeItem.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "Ítem Cadastrado com Sucesso", "CADASTRAR" ,JOptionPane.WARNING_MESSAGE);
                textNomeItem.setText("");
                itens.Atualiza();
            }
        }
    }//GEN-LAST:event_JBSalvarItemActionPerformed

    private void jBVoltarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarItemActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBVoltarItemActionPerformed

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed
        // TODO add your handling code here:
        new ListItem().setVisible(true);
    }//GEN-LAST:event_jBListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadItens().setVisible(true);
            }
        });
    }
    
    private ItemControl controItem;
    public ListItem itens;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalvarItem;
    private javax.swing.JButton jBListar;
    private javax.swing.JButton jBVoltarItem;
    private javax.swing.JLabel jLabelNomeItem;
    private javax.swing.JLabel jLabelTituloItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textNomeItem;
    // End of variables declaration//GEN-END:variables
}
