/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Luis
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadDoacao = new javax.swing.JButton();
        botaoCadPopular = new javax.swing.JButton();
        jBCadItens = new javax.swing.JButton();
        jBCadDoador = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jBCadAloj = new javax.swing.JButton();
        jBCadVagas = new javax.swing.JButton();
        jBCadFunc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        botaoCadDoacao.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        botaoCadDoacao.setText("Cadastrar Doação");
        botaoCadDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadDoacaoActionPerformed(evt);
            }
        });

        botaoCadPopular.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        botaoCadPopular.setText("Cadastro de Popular");
        botaoCadPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadPopularActionPerformed(evt);
            }
        });

        jBCadItens.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBCadItens.setText("Cadastrar Itens");
        jBCadItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadItensActionPerformed(evt);
            }
        });

        jBCadDoador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBCadDoador.setText("Cadastrar Doador");
        jBCadDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadDoadorActionPerformed(evt);
            }
        });

        jBFechar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jBCadAloj.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBCadAloj.setText("Cadastrar Alojamento");
        jBCadAloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadAlojActionPerformed(evt);
            }
        });

        jBCadVagas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBCadVagas.setText("Cadastrar Vagas");
        jBCadVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadVagasActionPerformed(evt);
            }
        });

        jBCadFunc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jBCadFunc.setText("Cadastrar Funcionário");
        jBCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadFuncActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setText("Lista Alojado por Pessoa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jBFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBCadAloj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadDoacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(botaoCadPopular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCadItens, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jBCadDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCadVagas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCadItens, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoCadDoacao, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jBCadDoador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadAloj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCadVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jBFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadDoacaoActionPerformed
        // TODO add your handling code here:
        
        CadDoacao caddoacao = new CadDoacao();
        caddoacao.setVisible(true);
    }//GEN-LAST:event_botaoCadDoacaoActionPerformed

    private void botaoCadPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadPopularActionPerformed
        // TODO add your handling code here:
        CadPessoa cadpessoa = new CadPessoa();
        cadpessoa.setVisible(true);
    }//GEN-LAST:event_botaoCadPopularActionPerformed

    private void jBCadItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadItensActionPerformed
        // TODO add your handling code here:
        CadItens cadItens = new CadItens();
        cadItens.setVisible(true);
    }//GEN-LAST:event_jBCadItensActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBCadDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadDoadorActionPerformed
        // TODO add your handling code here:
        CadDoador cadDoador = new CadDoador();
        cadDoador.setVisible(true);
    }//GEN-LAST:event_jBCadDoadorActionPerformed

    private void jBCadAlojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadAlojActionPerformed
        // TODO add your handling code here:
        CadAlojamento cadAloj = new CadAlojamento();
        cadAloj.setVisible(true);
    }//GEN-LAST:event_jBCadAlojActionPerformed

    private void jBCadVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadVagasActionPerformed
        // TODO add your handling code here:
         Vagas cadVagas = new Vagas();
         cadVagas.setVisible(true);
    }//GEN-LAST:event_jBCadVagasActionPerformed

    private void jBCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadFuncActionPerformed
        // TODO add your handling code here:
        CadFuncionario cadFunc = new CadFuncionario();
        cadFunc.setVisible(true);
    }//GEN-LAST:event_jBCadFuncActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ListAlojamento lisAloj = new ListAlojamento();
        lisAloj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadDoacao;
    private javax.swing.JButton botaoCadPopular;
    private javax.swing.JButton jBCadAloj;
    private javax.swing.JButton jBCadDoador;
    private javax.swing.JButton jBCadFunc;
    private javax.swing.JButton jBCadItens;
    private javax.swing.JButton jBCadVagas;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
